/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 16

#include "nimbase.h"
typedef NIM_CHAR TY98012[4096];
TY98012 buffer_98013;
NI64 size_98018;

N_NIMCALL(NI64, buffersize_98023)(void) {
	NI64 result;
	result = 0;
	result = size_98018;
	return result;
}

N_NIMCALL(NIM_CHAR, bufferread_98032)(NI64 index) {
	NIM_CHAR result;
	result = 0;
	result = buffer_98013[(index)- 0];
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_memoryInit000)(void) {
	size_98018 = IL64(0);
}

NIM_EXTERNC N_NOINLINE(void, HEX00_memoryDatInit000)(void) {
}

