/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 16

#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void) {
}

