/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 16

#include "nimbase.h"
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Avlnode25328 Avlnode25328;
typedef struct Gcheap45418 Gcheap45418;
typedef struct Gcstack45416 Gcstack45416;
typedef struct Cellseq43362 Cellseq43362;
typedef struct Cell43346 Cell43346;
typedef struct Cellset43358 Cellset43358;
typedef struct Pagedesc43354 Pagedesc43354;
typedef struct Memregion25330 Memregion25330;
typedef struct Smallchunk25282 Smallchunk25282;
typedef struct Llchunk25324 Llchunk25324;
typedef struct Bigchunk25284 Bigchunk25284;
typedef struct Intset25257 Intset25257;
typedef struct Trunk25253 Trunk25253;
typedef struct Gcstat45414 Gcstat45414;
typedef struct Basechunk25280 Basechunk25280;
typedef struct Freecell25272 Freecell25272;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimObject TNimObject;
typedef N_NIMCALL_PTR(NIM_BOOL, TY11421) (Exception* e);
typedef N_NIMCALL_PTR(NIM_BOOL, TY11426) (Exception* e);
typedef N_NIMCALL_PTR(void, TY11431) (void);
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
typedef Avlnode25328* TY25335[2];
struct  Avlnode25328  {
TY25335 link;
NI key;
NI upperbound;
NI level;
};
struct  Cellseq43362  {
NI len;
NI cap;
Cell43346** d;
};
struct  Cellset43358  {
NI counter;
NI max;
Pagedesc43354* head;
Pagedesc43354** data;
};
typedef Smallchunk25282* TY25345[512];
typedef Trunk25253* Trunkbuckets25255[256];
struct  Intset25257  {
Trunkbuckets25255 data;
};
struct  Memregion25330  {
NI minlargeobj;
NI maxlargeobj;
TY25345 freesmallchunks;
Llchunk25324* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25284* freechunkslist;
Intset25257 chunkstarts;
Avlnode25328* root;
Avlnode25328* deleted;
Avlnode25328* last;
Avlnode25328* freeavlnodes;
};
struct  Gcstat45414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap45418  {
Gcstack45416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq43362 zct;
Cellseq43362 decstack;
Cellset43358 cycleroots;
Cellseq43362 tempstack;
NI recgclock;
Memregion25330 region;
Gcstat45414 stat;
};
struct  Basechunk25280  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25282  {
  Basechunk25280 Sup;
Smallchunk25282* next;
Smallchunk25282* prev;
Freecell25272* freelist;
NI free;
NI acc;
NF data;
};
struct  Bigchunk25284  {
  Basechunk25280 Sup;
Bigchunk25284* next;
Bigchunk25284* prev;
NI align;
NF data;
};
typedef NI TY25261[16];
struct  Trunk25253  {
Trunk25253* next;
NI key;
TY25261 bits;
};
struct  Llchunk25324  {
NI size;
NI acc;
Llchunk25324* next;
};
typedef NF TY25204[4194304];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Freecell25272  {
Freecell25272* next;
NI zerofield;
};
struct  Cell43346  {
NI refcount;
TNimType* typ;
};
struct  Pagedesc43354  {
Pagedesc43354* next;
NI key;
TY25261 bits;
};
typedef N_NIMCALL_PTR(void, Finalizer) (void* self);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Gcstack45416  {
Gcstack45416* prev;
Gcstack45416* next;
void* starts;
void* pos;
NI maxstacksize;
};
static N_INLINE(void, initallocator_13001)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NIMCALL(void, initgc_12801)(void);
N_NIMCALL(void, init_43461)(Cellseq43362* s, NI cap);
N_NOCONV(void*, alloc0_8417)(NI size);
N_NIMCALL(void*, alloc0_42019)(Memregion25330* allocator, NI size);
N_NIMCALL(void*, alloc_41843)(Memregion25330* allocator, NI size);
N_NIMCALL(void*, rawalloc_32701)(Memregion25330* a, NI requestedsize);
static N_INLINE(NI, roundup_24201)(NI x, NI v);
N_NIMCALL(Smallchunk25282*, getsmallchunk_32024)(Memregion25330* a);
N_NIMCALL(Bigchunk25284*, getbigchunk_31217)(Memregion25330* a, NI size);
static N_INLINE(void, listremove_29002)(Bigchunk25284** head, Bigchunk25284* c);
N_NIMCALL(void, splitchunk_31015)(Memregion25330* a, Bigchunk25284* c, NI size);
static N_INLINE(void, updateprevsize_28083)(Memregion25330* a, Bigchunk25284* c, NI prevsize);
static N_INLINE(NIM_BOOL, isaccessible_28018)(Memregion25330* a, void* p);
N_NIMCALL(NIM_BOOL, contains_26759)(Intset25257* s, NI key);
N_NIMCALL(Trunk25253*, intsetget_26698)(Intset25257* t, NI key);
static N_INLINE(NI, pageindex_27259)(void* p);
N_NIMCALL(void, incl_26783)(Memregion25330* a, Intset25257* s, NI key);
N_NIMCALL(Trunk25253*, intsetput_26729)(Memregion25330* a, Intset25257* t, NI key);
N_NIMCALL(void*, llalloc_25455)(Memregion25330* a, NI size);
static N_INLINE(void*, osallocpages_25208)(NI size);
N_NOINLINE(void, raiseoutofmem_24033)(void);
static N_INLINE(void, inccurrmem_25405)(Memregion25330* a, NI bytes);
static N_INLINE(NI, pageindex_27251)(Basechunk25280* c);
static N_INLINE(void, listadd_30223)(Bigchunk25284** head, Bigchunk25284* c);
N_NIMCALL(Bigchunk25284*, requestoschunks_27277)(Memregion25330* a, NI size);
static N_INLINE(void, listadd_33616)(Smallchunk25282** head, Smallchunk25282* c);
static N_INLINE(void, listremove_36402)(Smallchunk25282** head, Smallchunk25282* c);
N_NIMCALL(void, add_26401)(Memregion25330* a, Avlnode25328** t, NI key, NI upperbound);
N_NIMCALL(Avlnode25328*, allocavlnode_25630)(Memregion25330* a, NI key, NI upperbound);
N_NIMCALL(void, skew_26376)(Avlnode25328** t);
N_NIMCALL(void, split_26384)(Avlnode25328** t);
N_NIMCALL(void, init_43482)(Cellset43358* s);
N_NIMCALL(NI, getRefcount)(void* p);
static N_INLINE(Cell43346*, usrtocell_47046)(void* usr);
N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space);
N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size);
N_NIMCALL(void*, rawnewobj_53204)(TNimType* typ, NI size, Gcheap45418* gch);
N_NIMCALL(void, collectct_47410)(Gcheap45418* gch);
N_NOINLINE(NI, stacksize_67201)(void);
static N_INLINE(NI, getoccupiedmem_43268)(Memregion25330* a);
N_NIMCALL(void, collectctbody_71021)(Gcheap45418* gch);
static N_INLINE(void, prepareforinteriorpointerchecking_40694)(Memregion25330* a);
N_NIMCALL(NI, lowgauge_26218)(Avlnode25328* n);
N_NIMCALL(NI, highgauge_26244)(Avlnode25328* n);
N_CDECL(void, markstackandregisters_68440)(Gcheap45418* gch);
static N_INLINE(void, gcmark_66246)(Gcheap45418* gch, void* p);
N_NIMCALL(void*, interiorallocatedptr_40701)(Memregion25330* a, void* p);
static N_INLINE(Basechunk25280*, pageaddr_27267)(void* p);
static N_INLINE(NIM_BOOL, chunkunused_27131)(Basechunk25280* c);
static N_INLINE(NIM_BOOL, issmallchunk_27108)(Basechunk25280* c);
N_NIMCALL(Avlnode25328*, inrange_26314)(Avlnode25328* root, NI key);
static N_INLINE(void, add_43437)(Cellseq43362* s, Cell43346* c);
N_NOCONV(void*, alloc_8401)(NI size);
N_NOCONV(void, dealloc_8448)(void* p);
N_NIMCALL(void, dealloc_42028)(Memregion25330* allocator, void* p);
N_NIMCALL(void, rawdealloc_39023)(Memregion25330* a, void* p);
N_NIMCALL(void, freebigchunk_28206)(Memregion25330* a, Bigchunk25284* c_28210);
N_NIMCALL(void, excl_26797)(Intset25257* s, NI key);
N_NIMCALL(void, freeoschunks_27810)(Memregion25330* a, void* p, NI size);
static N_INLINE(void, osdeallocpages_25227)(void* p, NI size);
static N_INLINE(void, deccurrmem_25422)(Memregion25330* a, NI bytes);
N_NIMCALL(void, del_26604)(Memregion25330* a, Avlnode25328** t, NI x);
static N_INLINE(void, deallocavlnode_26206)(Memregion25330* a, Avlnode25328* n);
N_NIMCALL(void, markthreadstacks_66806)(Gcheap45418* gch);
N_NIMCALL(NIM_BOOL, collectzct_65612)(Gcheap45418* gch);
static N_INLINE(NIM_BOOL, canbecycleroot_47067)(Cell43346* c);
N_NIMCALL(void, excl_44095)(Cellset43358* s, Cell43346* cell);
N_NIMCALL(Pagedesc43354*, cellsetget_43529)(Cellset43358 t, NI key);
static N_INLINE(NI, nexttry_43521)(NI h, NI maxhash);
N_NIMCALL(void, preparedealloc_47608)(Cell43346* cell);
static N_INLINE(void*, celltousr_47025)(Cell43346* cell);
N_NIMCALL(void, forallchildren_47417)(Cell43346* cell, NU8 op);
N_NIMCALL(void, forallchildrenaux_47425)(void* dest, TNimType* mt, NU8 op);
N_NIMCALL(void, dooperation_47421)(void* p, NU8 op);
static N_INLINE(void, decref_49004)(Cell43346* c);
static N_INLINE(void, rtladdzct_48604)(Cell43346* c);
N_NOINLINE(void, addzct_47017)(Cellseq43362* s, Cell43346* c);
static N_INLINE(void, rtladdcycleroot_47823)(Cell43346* c);
N_NOINLINE(void, incl_44065)(Cellset43358* s, Cell43346* cell);
N_NIMCALL(Pagedesc43354*, cellsetput_43863)(Cellset43358* t, NI key);
N_NIMCALL(void, cellsetenlarge_43812)(Cellset43358* t);
N_NIMCALL(void, cellsetrawinsert_43558)(Cellset43358 t, Pagedesc43354** data, Pagedesc43354* desc);
N_NIMCALL(void, markgray_62605)(Cell43346* s);
N_NIMCALL(void, scan_63004)(Cell43346* s);
N_NIMCALL(void, scanblack_62804)(Cell43346* s);
N_NIMCALL(void, collectwhite_63204)(Cell43346* s);
N_NIMCALL(NIM_BOOL, isallocatedptr_32405)(Memregion25330* a, void* p);
N_NIMCALL(void, freecycliccell_61827)(Gcheap45418* gch, Cell43346* c);
N_NIMCALL(void, forallslotsaux_51608)(void* dest, TNimNode* n, NU8 op);
N_NIMCALL(TNimNode*, selectbranch_23610)(void* aa, TNimNode* n);
N_NIMCALL(NI, getdiscriminant_23204)(void* aa, TNimNode* n);
N_NIMCALL(void, collectcycles_65844)(Gcheap45418* gch);
N_NIMCALL(void, markroots_63405)(Gcheap45418* gch);
N_NIMCALL(void, collectroots_65801)(Gcheap45418* gch);
N_NIMCALL(void, cellsetreset_51601)(Cellset43358* s);
N_NIMCALL(void, deinit_43493)(Cellset43358* s);
N_NIMCALL(NI, getoccupiedmem_9091)(void);
N_NIMCALL(NI, gettotalmem_9095)(void);
N_NIMCALL(NI, getfreemem_9093)(void);
N_NIMCALL(void, unmarkstackandregisters_70811)(Gcheap45418* gch);
static N_INLINE(void, addnewobjtozct_52687)(Cell43346* res, Gcheap45418* gch);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
STRING_LITERAL(TMP2, "out of memory", 13);
NIM_BOOL nimvm_6690;
NI nim_program_result;
TY11421 globalraisehook_11425;
TY11426 localraisehook_11430;
TY11431 outofmemhook_11433;
TNimType strdesc_13601;
TY25204 theheap_25205;
NI bumppointer_25207;
Avlnode25328 bottomdata_25361;
Avlnode25328* bottom_25362;
Gcheap45418 gch_45459;
NIM_BOOL localgcinitialized_67237;
NIM_CHAR decimalpoint_76450;

static N_INLINE(void, initallocator_13001)(void) {
	bottom_25362 = (&bottomdata_25361);
	(*bottom_25362).link[(((NI) 0))- 0] = bottom_25362;
	(*bottom_25362).link[(((NI) 1))- 0] = bottom_25362;
}

N_NOINLINE(void, setStackBottom)(void* thestackbottom) {
	{
		if (!(gch_45459.stackbottom == NIM_NIL)) goto LA3;
		gch_45459.stackbottom = thestackbottom;
	}
	goto LA1;
	LA3: ;
	{
		NI a;
		NI b;
		a = ((NI) (thestackbottom));
		b = ((NI) (gch_45459.stackbottom));
		gch_45459.stackbottom = ((void*) (((a >= b) ? a : b)));
	}
	LA1: ;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) ((&locals)));
	setStackBottom(locals);
}

static N_INLINE(NI, roundup_24201)(NI x, NI v) {
	NI result;
	result = 0;
	result = (NI)((NI)(x + (NI)(v - ((NI) 1))) & (NI)((NU32) ~((NI)(v - ((NI) 1)))));
	return result;
}

static N_INLINE(void, listremove_29002)(Bigchunk25284** head, Bigchunk25284* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Trunk25253*, intsetget_26698)(Intset25257* t, NI key) {
	Trunk25253* result;
	Trunk25253* it;
{	result = 0;
	it = (*t).data[((NI)(key & ((NI) 255)))- 0];
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			{
				if (!((*it).key == key)) goto LA5;
				result = it;
				goto BeforeRet;
			}
			LA5: ;
			it = (*it).next;
		} LA2: ;
	}
	result = NIM_NIL;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, contains_26759)(Intset25257* s, NI key) {
	NIM_BOOL result;
	Trunk25253* t;
	result = 0;
	t = intsetget_26698(s, (NI)((NU32)(key) >> (NU32)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		result = !(((NI)((*t).bits[((NI)((NU32)(((NI) (u))) >> (NU32)(((NI) 5))))- 0] & (NI)((NU32)(((NI) 1)) << (NU32)(((NI) ((NI)(((NI) (u)) & ((NI) 31))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, pageindex_27259)(void* p) {
	NI result;
	result = 0;
	result = (NI)((NU32)(((NI) (p))) >> (NU32)(((NI) 12)));
	return result;
}

static N_INLINE(NIM_BOOL, isaccessible_28018)(Memregion25330* a, void* p) {
	NIM_BOOL result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = pageindex_27259(p);
	result = contains_26759((&(*a).chunkstarts), LOC1);
	return result;
}

static N_INLINE(void, updateprevsize_28083)(Memregion25330* a, Bigchunk25284* c, NI prevsize) {
	Basechunk25280* ri;
	ri = ((Basechunk25280*) ((NI)((NU32)(((NI) (c))) + (NU32)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_28018((&(*a)), ((void*) (ri)));
		if (!LOC3) goto LA4;
		(*ri).prevsize = prevsize;
	}
	LA4: ;
}

N_NOINLINE(void, raiseoutofmem_24033)(void) {
	{
		if (!!((outofmemhook_11433 == NIM_NIL))) goto LA3;
		outofmemhook_11433();
	}
	LA3: ;
	printf("%s\012", ((NimStringDesc*) &TMP2)? (((NimStringDesc*) &TMP2))->data:"nil");
	exit(((NI) 1));
}

static N_INLINE(void*, osallocpages_25208)(NI size) {
	void* result;
	result = 0;
	{
		if (!((NI)(size + bumppointer_25207) < (NI)(((NI) (theheap_25205)) + ((NI)sizeof(TY25204))))) goto LA3;
		result = ((void*) (bumppointer_25207));
		bumppointer_25207 += size;
	}
	goto LA1;
	LA3: ;
	{
		raiseoutofmem_24033();
	}
	LA1: ;
	return result;
}

static N_INLINE(void, inccurrmem_25405)(Memregion25330* a, NI bytes) {
	(*a).currmem += bytes;
}

N_NIMCALL(void*, llalloc_25455)(Memregion25330* a, NI size) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Llchunk25324* old;
		void* LOC7;
		LOC3 = 0;
		LOC3 = ((*a).llmem == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*a).llmem).size < size);
		LA4: ;
		if (!LOC3) goto LA5;
		old = (*a).llmem;
		LOC7 = 0;
		LOC7 = osallocpages_25208(((NI) 4096));
		(*a).llmem = ((Llchunk25324*) (LOC7));
		inccurrmem_25405(a, ((NI) 4096));
		(*(*a).llmem).size = (NI)(((NI) 4096) - ((NI)sizeof(Llchunk25324)));
		(*(*a).llmem).acc = ((NI)sizeof(Llchunk25324));
		(*(*a).llmem).next = old;
	}
	LA5: ;
	result = ((void*) ((NI)(((NI) ((*a).llmem)) + (*(*a).llmem).acc)));
	(*(*a).llmem).size -= size;
	(*(*a).llmem).acc += size;
	zeroMem(result, ((NI) (size)));
	return result;
}

N_NIMCALL(Trunk25253*, intsetput_26729)(Memregion25330* a, Intset25257* t, NI key) {
	Trunk25253* result;
	result = 0;
	result = intsetget_26698((&(*t)), key);
	{
		void* LOC5;
		if (!(result == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = llalloc_25455(a, ((NI)sizeof(Trunk25253)));
		result = ((Trunk25253*) (LOC5));
		(*result).next = (*t).data[((NI)(key & ((NI) 255)))- 0];
		(*t).data[((NI)(key & ((NI) 255)))- 0] = result;
		(*result).key = key;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, incl_26783)(Memregion25330* a, Intset25257* s, NI key) {
	Trunk25253* t;
	NI u;
	t = intsetput_26729(a, s, (NI)((NU32)(key) >> (NU32)(((NI) 9))));
	u = (NI)(key & ((NI) 511));
	(*t).bits[((NI)((NU32)(((NI) (u))) >> (NU32)(((NI) 5))))- 0] = (NI)((*t).bits[((NI)((NU32)(((NI) (u))) >> (NU32)(((NI) 5))))- 0] | (NI)((NU32)(((NI) 1)) << (NU32)(((NI) ((NI)(((NI) (u)) & ((NI) 31)))))));
}

static N_INLINE(NI, pageindex_27251)(Basechunk25280* c) {
	NI result;
	result = 0;
	result = (NI)((NU32)(((NI) (c))) >> (NU32)(((NI) 12)));
	return result;
}

static N_INLINE(void, listadd_30223)(Bigchunk25284** head, Bigchunk25284* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

N_NIMCALL(void, splitchunk_31015)(Memregion25330* a, Bigchunk25284* c, NI size) {
	Bigchunk25284* rest;
	Basechunk25280* LOC1;
	NI LOC2;
	rest = ((Bigchunk25284*) ((NI)((NU32)(((NI) (c))) + (NU32)(size))));
	(*rest).Sup.size = (NI)((*c).Sup.size - size);
	(*rest).Sup.used = NIM_FALSE;
	(*rest).next = NIM_NIL;
	(*rest).prev = NIM_NIL;
	(*rest).Sup.prevsize = size;
	updateprevsize_28083(a, c, (*rest).Sup.size);
	(*c).Sup.size = size;
	LOC1 = 0;
	LOC1 = &rest->Sup;
	LOC2 = 0;
	LOC2 = pageindex_27251(LOC1);
	incl_26783(a, (&(*a).chunkstarts), LOC2);
	listadd_30223(&(*a).freechunkslist, rest);
}

N_NIMCALL(Bigchunk25284*, requestoschunks_27277)(Memregion25330* a, NI size) {
	Bigchunk25284* result;
	void* LOC1;
	NI nxt;
	Basechunk25280* next;
	NI lastsize;
	NI prv;
	Basechunk25280* prev;
	result = 0;
	inccurrmem_25405(a, size);
	(*a).freemem += size;
	LOC1 = 0;
	LOC1 = osallocpages_25208(size);
	result = ((Bigchunk25284*) (LOC1));
	(*result).next = NIM_NIL;
	(*result).prev = NIM_NIL;
	(*result).Sup.used = NIM_FALSE;
	(*result).Sup.size = size;
	nxt = (NI)((NU32)(((NI) (result))) + (NU32)(size));
	next = ((Basechunk25280*) (nxt));
	{
		NI LOC4;
		NIM_BOOL LOC5;
		LOC4 = 0;
		LOC4 = pageindex_27251(next);
		LOC5 = 0;
		LOC5 = contains_26759((&(*a).chunkstarts), LOC4);
		if (!LOC5) goto LA6;
		(*next).prevsize = size;
	}
	LA6: ;
	{
		if (!!(((*a).lastsize == ((NI) 0)))) goto LA10;
		lastsize = (*a).lastsize;
	}
	goto LA8;
	LA10: ;
	{
		lastsize = ((NI) 4096);
	}
	LA8: ;
	prv = (NI)((NU32)(((NI) (result))) - (NU32)(lastsize));
	prev = ((Basechunk25280*) (prv));
	{
		NIM_BOOL LOC15;
		NI LOC16;
		LOC15 = 0;
		LOC16 = 0;
		LOC16 = pageindex_27251(prev);
		LOC15 = contains_26759((&(*a).chunkstarts), LOC16);
		if (!(LOC15)) goto LA17;
		LOC15 = ((*prev).size == lastsize);
		LA17: ;
		if (!LOC15) goto LA18;
		(*result).Sup.prevsize = lastsize;
	}
	goto LA13;
	LA18: ;
	{
		(*result).Sup.prevsize = ((NI) 0);
	}
	LA13: ;
	(*a).lastsize = size;
	return result;
}

N_NIMCALL(Bigchunk25284*, getbigchunk_31217)(Memregion25330* a, NI size) {
	Bigchunk25284* result;
	Basechunk25280* LOC16;
	NI LOC17;
	result = 0;
	result = (*a).freechunkslist;
	{
		{
			while (1) {
				if (!!((result == NIM_NIL))) goto LA3;
				{
					if (!((*result).Sup.size == size)) goto LA6;
					listremove_29002(&(*a).freechunkslist, result);
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					if (!(size < (*result).Sup.size)) goto LA9;
					listremove_29002(&(*a).freechunkslist, result);
					splitchunk_31015(a, result, size);
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				result = (*result).next;
			} LA3: ;
		}
		{
			if (!(size < ((NI) 524288))) goto LA13;
			result = requestoschunks_27277(a, ((NI) 524288));
			splitchunk_31015(a, result, size);
		}
		goto LA11;
		LA13: ;
		{
			result = requestoschunks_27277(a, size);
		}
		LA11: ;
	} LA1: ;
	(*result).Sup.prevsize = ((NI) 0);
	(*result).Sup.used = NIM_TRUE;
	LOC16 = 0;
	LOC16 = &result->Sup;
	LOC17 = 0;
	LOC17 = pageindex_27251(LOC16);
	incl_26783(a, (&(*a).chunkstarts), LOC17);
	(*a).freemem -= size;
	return result;
}

N_NIMCALL(Smallchunk25282*, getsmallchunk_32024)(Memregion25330* a) {
	Smallchunk25282* result;
	Bigchunk25284* res;
	result = 0;
	res = getbigchunk_31217(a, ((NI) 4096));
	result = ((Smallchunk25282*) (res));
	return result;
}

static N_INLINE(void, listadd_33616)(Smallchunk25282** head, Smallchunk25282* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

static N_INLINE(void, listremove_36402)(Smallchunk25282** head, Smallchunk25282* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Avlnode25328*, allocavlnode_25630)(Memregion25330* a, NI key, NI upperbound) {
	Avlnode25328* result;
	result = 0;
	{
		if (!!(((*a).freeavlnodes == NIM_NIL))) goto LA3;
		result = (*a).freeavlnodes;
		(*a).freeavlnodes = (*(*a).freeavlnodes).link[(((NI) 0))- 0];
	}
	goto LA1;
	LA3: ;
	{
		void* LOC6;
		LOC6 = 0;
		LOC6 = llalloc_25455(a, ((NI)sizeof(Avlnode25328)));
		result = ((Avlnode25328*) (LOC6));
	}
	LA1: ;
	(*result).key = key;
	(*result).upperbound = upperbound;
	(*result).link[(((NI) 0))- 0] = bottom_25362;
	(*result).link[(((NI) 1))- 0] = bottom_25362;
	(*result).level = ((NI) 1);
	return result;
}

N_NIMCALL(void, skew_26376)(Avlnode25328** t) {
	{
		Avlnode25328* temp;
		if (!((*(*(*t)).link[(((NI) 0))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 0))- 0];
		(*temp).link[(((NI) 0))- 0] = (*(*t)).link[(((NI) 1))- 0];
		(*(*t)).link[(((NI) 1))- 0] = temp;
	}
	LA3: ;
}

N_NIMCALL(void, split_26384)(Avlnode25328** t) {
	{
		Avlnode25328* temp;
		if (!((*(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		(*temp).link[(((NI) 1))- 0] = (*(*t)).link[(((NI) 0))- 0];
		(*(*t)).link[(((NI) 0))- 0] = temp;
		(*(*t)).level += ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(void, add_26401)(Memregion25330* a, Avlnode25328** t, NI key, NI upperbound) {
	{
		if (!((*t) == bottom_25362)) goto LA3;
		(*t) = allocavlnode_25630(a, key, upperbound);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((NU32)(key) < (NU32)((*(*t)).key))) goto LA8;
			add_26401(a, &(*(*t)).link[(((NI) 0))- 0], key, upperbound);
		}
		goto LA6;
		LA8: ;
		{
			if (!((NU32)((*(*t)).key) < (NU32)(key))) goto LA11;
			add_26401(a, &(*(*t)).link[(((NI) 1))- 0], key, upperbound);
		}
		goto LA6;
		LA11: ;
		{
		}
		LA6: ;
		skew_26376(t);
		split_26384(t);
	}
	LA1: ;
}

N_NIMCALL(void*, rawalloc_32701)(Memregion25330* a, NI requestedsize) {
	void* result;
	NI size;
	result = 0;
	size = roundup_24201(requestedsize, ((NI) 8));
	{
		NI s;
		Smallchunk25282* c;
		if (!(size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))))) goto LA3;
		s = (NI)(size / ((NI) 8));
		c = (*a).freesmallchunks[(s)- 0];
		{
			if (!(c == NIM_NIL)) goto LA7;
			c = getsmallchunk_32024(a);
			(*c).freelist = NIM_NIL;
			(*c).Sup.size = size;
			(*c).acc = size;
			(*c).free = (NI)((NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))) - size);
			(*c).next = NIM_NIL;
			(*c).prev = NIM_NIL;
			listadd_33616(&(*a).freesmallchunks[(s)- 0], c);
			result = ((void*) ((&(*c).data)));
		}
		goto LA5;
		LA7: ;
		{
			{
				if (!((*c).freelist == NIM_NIL)) goto LA12;
				result = ((void*) ((NI)((NU32)(((NI) ((&(*c).data)))) + (NU32)((*c).acc))));
				(*c).acc += size;
			}
			goto LA10;
			LA12: ;
			{
				result = ((void*) ((*c).freelist));
				(*c).freelist = (*(*c).freelist).next;
			}
			LA10: ;
			(*c).free -= size;
		}
		LA5: ;
		{
			if (!((*c).free < size)) goto LA17;
			listremove_36402(&(*a).freesmallchunks[(s)- 0], c);
		}
		LA17: ;
	}
	goto LA1;
	LA3: ;
	{
		Bigchunk25284* c;
		size = roundup_24201((NI)(requestedsize + (NI)(((NI)sizeof(Bigchunk25284)) - ((NI) 8))), ((NI) 4096));
		c = getbigchunk_31217(a, size);
		result = ((void*) ((&(*c).data)));
		{
			if (!((*a).root == NIM_NIL)) goto LA22;
			(*a).root = bottom_25362;
		}
		LA22: ;
		add_26401(a, &(*a).root, ((NI) (result)), (NI)((NU32)(((NI) (result))) + (NU32)(size)));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void*, alloc_41843)(Memregion25330* allocator, NI size) {
	void* result;
	result = 0;
	result = rawalloc_32701(allocator, (NI)(((NI) (size)) + ((NI)sizeof(Freecell25272))));
	(*((Freecell25272*) (result))).zerofield = ((NI) 1);
	result = ((void*) ((NI)((NU32)(((NI) (result))) + (NU32)(((NI)sizeof(Freecell25272))))));
	return result;
}

N_NIMCALL(void*, alloc0_42019)(Memregion25330* allocator, NI size) {
	void* result;
	result = 0;
	result = alloc_41843(allocator, size);
	zeroMem(result, size);
	return result;
}

N_NOCONV(void*, alloc0_8417)(NI size) {
	void* result;
	result = 0;
	result = alloc0_42019((&gch_45459.region), size);
	return result;
}

N_NIMCALL(void, init_43461)(Cellseq43362* s, NI cap) {
	void* LOC1;
	(*s).len = ((NI) 0);
	(*s).cap = cap;
	LOC1 = 0;
	LOC1 = alloc0_8417(((NI) ((NI)(cap * ((NI) 4)))));
	(*s).d = ((Cell43346**) (LOC1));
}

N_NIMCALL(void, init_43482)(Cellset43358* s) {
	void* LOC1;
	LOC1 = 0;
	LOC1 = alloc0_8417(((NI) 4096));
	(*s).data = ((Pagedesc43354**) (LOC1));
	(*s).max = ((NI) 1023);
	(*s).counter = ((NI) 0);
	(*s).head = NIM_NIL;
}

N_NIMCALL(void, initgc_12801)(void) {
	gch_45459.cyclethreshold = ((NI) 4194304);
	gch_45459.stat.stackscans = ((NI) 0);
	gch_45459.stat.cyclecollections = ((NI) 0);
	gch_45459.stat.maxthreshold = ((NI) 0);
	gch_45459.stat.maxstacksize = ((NI) 0);
	gch_45459.stat.maxstackcells = ((NI) 0);
	gch_45459.stat.cycletablesize = ((NI) 0);
	init_43461((&gch_45459.zct), ((NI) 1024));
	init_43461((&gch_45459.tempstack), ((NI) 1024));
	init_43482((&gch_45459.cycleroots));
	init_43461((&gch_45459.decstack), ((NI) 1024));
}

static N_INLINE(Cell43346*, usrtocell_47046)(void* usr) {
	Cell43346* result;
	result = 0;
	result = ((Cell43346*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Cell43346))))));
	return result;
}

N_NIMCALL(NI, getRefcount)(void* p) {
	NI result;
	Cell43346* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = usrtocell_47046(p);
	result = (NI)((NU32)((*LOC1).refcount) >> (NU32)(((NI) 3)));
	return result;
}

N_NOINLINE(NI, stacksize_67201)(void) {
	NI result;
	void* volatile stacktop;
	result = 0;
	stacktop = 0;
	result = ((NI)(((NI) ((&stacktop))) - ((NI) (gch_45459.stackbottom))) > 0? ((NI)(((NI) ((&stacktop))) - ((NI) (gch_45459.stackbottom)))) : -((NI)(((NI) ((&stacktop))) - ((NI) (gch_45459.stackbottom)))));
	return result;
}

static N_INLINE(NI, getoccupiedmem_43268)(Memregion25330* a) {
	NI result;
	result = 0;
	result = (NI)((*a).currmem - (*a).freemem);
	return result;
}

N_NIMCALL(NI, lowgauge_26218)(Avlnode25328* n) {
	NI result;
	Avlnode25328* it;
	result = 0;
	it = n;
	{
		while (1) {
			if (!!((it == bottom_25362))) goto LA2;
			result = (*it).key;
			it = (*it).link[(((NI) 0))- 0];
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, highgauge_26244)(Avlnode25328* n) {
	NI result;
	Avlnode25328* it;
	result = 0;
	result = ((NI) -1);
	it = n;
	{
		while (1) {
			if (!!((it == bottom_25362))) goto LA2;
			result = (*it).upperbound;
			it = (*it).link[(((NI) 1))- 0];
		} LA2: ;
	}
	return result;
}

static N_INLINE(void, prepareforinteriorpointerchecking_40694)(Memregion25330* a) {
	(*a).minlargeobj = lowgauge_26218((*a).root);
	(*a).maxlargeobj = highgauge_26244((*a).root);
}

static N_INLINE(Basechunk25280*, pageaddr_27267)(void* p) {
	Basechunk25280* result;
	result = 0;
	result = ((Basechunk25280*) ((NI)(((NI) (p)) & ((NI) -4096))));
	return result;
}

static N_INLINE(NIM_BOOL, chunkunused_27131)(Basechunk25280* c) {
	NIM_BOOL result;
	result = 0;
	result = !((*c).used);
	return result;
}

static N_INLINE(NIM_BOOL, issmallchunk_27108)(Basechunk25280* c) {
	NIM_BOOL result;
{	result = 0;
	result = ((*c).size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Avlnode25328*, inrange_26314)(Avlnode25328* root, NI key) {
	Avlnode25328* result;
	Avlnode25328* it;
{	result = 0;
	it = root;
	{
		while (1) {
			if (!!((it == bottom_25362))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = ((NU32)((*it).key) <= (NU32)(key));
				if (!(LOC5)) goto LA6;
				LOC5 = ((NU32)(key) < (NU32)((*it).upperbound));
				LA6: ;
				if (!LOC5) goto LA7;
				result = it;
				goto BeforeRet;
			}
			LA7: ;
			it = (*it).link[(((NU32)((*it).key) < (NU32)(key)))- 0];
		} LA2: ;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void*, interiorallocatedptr_40701)(Memregion25330* a, void* p) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk25280* c_40706;
		LOC3 = 0;
		LOC3 = isaccessible_28018(a, p);
		if (!LOC3) goto LA4;
		c_40706 = pageaddr_27267(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_27131(c_40706);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk25282* c;
				NI offset;
				LOC13 = 0;
				LOC13 = issmallchunk_27108(c_40706);
				if (!LOC13) goto LA14;
				c = ((Smallchunk25282*) (c_40706));
				offset = (NI)((NU32)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU32)((NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))));
				{
					Freecell25272* d;
					if (!((NU32)(offset) < (NU32)((*c).acc))) goto LA18;
					d = ((Freecell25272*) ((NI)((NU32)((NI)((NU32)(((NI) ((&(*c).data)))) + (NU32)(offset))) - (NU32)((NI)((NU32)(offset) % (NU32)((*c).Sup.size))))));
					{
						if (!((NU32)(((NI) 1)) < (NU32)((*d).zerofield))) goto LA22;
						result = ((void*) (d));
					}
					LA22: ;
				}
				LA18: ;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk25284* c;
				NF* d;
				c = ((Bigchunk25284*) (c_40706));
				d = (&(*c).data);
				{
					NIM_BOOL LOC27;
					LOC27 = 0;
					LOC27 = (((void*) (d)) <= p);
					if (!(LOC27)) goto LA28;
					LOC27 = ((NU32)(((NI) 1)) < (NU32)((*((Freecell25272*) (d))).zerofield));
					LA28: ;
					if (!LOC27) goto LA29;
					result = ((void*) (d));
				}
				LA29: ;
			}
			LA11: ;
		}
		LA9: ;
	}
	goto LA1;
	LA4: ;
	{
		NI q;
		q = ((NI) (p));
		{
			NIM_BOOL LOC34;
			Avlnode25328* avlnode;
			LOC34 = 0;
			LOC34 = ((NU32)((*a).minlargeobj) <= (NU32)(q));
			if (!(LOC34)) goto LA35;
			LOC34 = ((NU32)(q) <= (NU32)((*a).maxlargeobj));
			LA35: ;
			if (!LOC34) goto LA36;
			avlnode = inrange_26314((*a).root, q);
			{
				void* k;
				Bigchunk25284* c;
				Basechunk25280* LOC42;
				if (!!((avlnode == NIM_NIL))) goto LA40;
				k = ((void*) ((*avlnode).key));
				LOC42 = 0;
				LOC42 = pageaddr_27267(k);
				c = ((Bigchunk25284*) (LOC42));
				{
					if (!((NU32)(((NI) 1)) < (NU32)((*((Freecell25272*) (k))).zerofield))) goto LA45;
					result = k;
				}
				LA45: ;
			}
			LA40: ;
		}
		LA36: ;
	}
	LA1: ;
	return result;
}

N_NOCONV(void*, alloc_8401)(NI size) {
	void* result;
	result = 0;
	result = alloc_41843((&gch_45459.region), size);
	return result;
}

N_NIMCALL(void, excl_26797)(Intset25257* s, NI key) {
	Trunk25253* t;
	t = intsetget_26698((&(*s)), (NI)((NU32)(key) >> (NU32)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		(*t).bits[((NI)((NU32)(((NI) (u))) >> (NU32)(((NI) 5))))- 0] = (NI)((*t).bits[((NI)((NU32)(((NI) (u))) >> (NU32)(((NI) 5))))- 0] & (NI)((NU32) ~((NI)((NU32)(((NI) 1)) << (NU32)(((NI) ((NI)(((NI) (u)) & ((NI) 31)))))))));
	}
	LA3: ;
}

static N_INLINE(void, osdeallocpages_25227)(void* p, NI size) {
	{
		if (!((NI)(bumppointer_25207 - size) == ((NI) (p)))) goto LA3;
		bumppointer_25207 -= size;
	}
	LA3: ;
}

static N_INLINE(void, deccurrmem_25422)(Memregion25330* a, NI bytes) {
	(*a).maxmem = (((*a).maxmem >= (*a).currmem) ? (*a).maxmem : (*a).currmem);
	(*a).currmem -= bytes;
}

N_NIMCALL(void, freeoschunks_27810)(Memregion25330* a, void* p, NI size) {
	Basechunk25280* c;
	NI nxt;
	Basechunk25280* next;
	NI LOC7;
	c = ((Basechunk25280*) (p));
	nxt = (NI)((NU32)(((NI) (p))) + (NU32)((*c).size));
	next = ((Basechunk25280*) (nxt));
	{
		NI LOC3;
		NIM_BOOL LOC4;
		LOC3 = 0;
		LOC3 = pageindex_27251(next);
		LOC4 = 0;
		LOC4 = contains_26759((&(*a).chunkstarts), LOC3);
		if (!LOC4) goto LA5;
		(*next).prevsize = ((NI) 0);
	}
	LA5: ;
	LOC7 = 0;
	LOC7 = pageindex_27259(p);
	excl_26797((&(*a).chunkstarts), LOC7);
	osdeallocpages_25227(p, size);
	deccurrmem_25422(a, size);
	(*a).freemem -= size;
}

N_NIMCALL(void, freebigchunk_28206)(Memregion25330* a, Bigchunk25284* c_28210) {
	Bigchunk25284* c;
	Basechunk25280* ri;
	c = c_28210;
	(*a).freemem += (*c).Sup.size;
	ri = ((Basechunk25280*) ((NI)((NU32)(((NI) (c))) + (NU32)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_28018((&(*a)), ((void*) (ri)));
		if (!(LOC3)) goto LA4;
		LOC3 = chunkunused_27131(ri);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC12;
			LOC9 = 0;
			LOC9 = issmallchunk_27108(ri);
			if (!!(LOC9)) goto LA10;
			listremove_29002(&(*a).freechunkslist, ((Bigchunk25284*) (ri)));
			(*c).Sup.size += (*ri).size;
			LOC12 = 0;
			LOC12 = pageindex_27251(ri);
			excl_26797((&(*a).chunkstarts), LOC12);
		}
		LA10: ;
	}
	LA5: ;
	{
		Basechunk25280* le;
		if (!!(((*c).Sup.prevsize == ((NI) 0)))) goto LA15;
		le = ((Basechunk25280*) ((NI)((NU32)(((NI) (c))) - (NU32)((*c).Sup.prevsize))));
		{
			NIM_BOOL LOC19;
			LOC19 = 0;
			LOC19 = isaccessible_28018((&(*a)), ((void*) (le)));
			if (!(LOC19)) goto LA20;
			LOC19 = chunkunused_27131(le);
			LA20: ;
			if (!LOC19) goto LA21;
			{
				NIM_BOOL LOC25;
				Basechunk25280* LOC28;
				NI LOC29;
				LOC25 = 0;
				LOC25 = issmallchunk_27108(le);
				if (!!(LOC25)) goto LA26;
				listremove_29002(&(*a).freechunkslist, ((Bigchunk25284*) (le)));
				(*le).size += (*c).Sup.size;
				LOC28 = 0;
				LOC28 = &c->Sup;
				LOC29 = 0;
				LOC29 = pageindex_27251(LOC28);
				excl_26797((&(*a).chunkstarts), LOC29);
				c = ((Bigchunk25284*) (le));
			}
			LA26: ;
		}
		LA21: ;
	}
	LA15: ;
	{
		NIM_BOOL LOC32;
		Basechunk25280* LOC36;
		NI LOC37;
		LOC32 = 0;
		LOC32 = ((*c).Sup.size < ((NI) 1048576));
		if (LOC32) goto LA33;
		LOC32 = NIM_TRUE;
		LA33: ;
		if (!LOC32) goto LA34;
		LOC36 = 0;
		LOC36 = &c->Sup;
		LOC37 = 0;
		LOC37 = pageindex_27251(LOC36);
		incl_26783(a, (&(*a).chunkstarts), LOC37);
		updateprevsize_28083(a, c, (*c).Sup.size);
		listadd_30223(&(*a).freechunkslist, c);
		(*c).Sup.used = NIM_FALSE;
	}
	goto LA30;
	LA34: ;
	{
		freeoschunks_27810(a, ((void*) (c)), (*c).Sup.size);
	}
	LA30: ;
}

static N_INLINE(void, deallocavlnode_26206)(Memregion25330* a, Avlnode25328* n) {
	(*n).link[(((NI) 0))- 0] = (*a).freeavlnodes;
	(*a).freeavlnodes = n;
}

N_NIMCALL(void, del_26604)(Memregion25330* a, Avlnode25328** t, NI x) {
{	{
		if (!((*t) == bottom_25362)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	(*a).last = (*t);
	{
		if (!((NU32)(x) < (NU32)((*(*t)).key))) goto LA7;
		del_26604(a, &(*(*t)).link[(((NI) 0))- 0], x);
	}
	goto LA5;
	LA7: ;
	{
		(*a).deleted = (*t);
		del_26604(a, &(*(*t)).link[(((NI) 1))- 0], x);
	}
	LA5: ;
	{
		NIM_BOOL LOC12;
		NIM_BOOL LOC13;
		LOC12 = 0;
		LOC13 = 0;
		LOC13 = ((*t) == (*a).last);
		if (!(LOC13)) goto LA14;
		LOC13 = !(((*a).deleted == bottom_25362));
		LA14: ;
		LOC12 = LOC13;
		if (!(LOC12)) goto LA15;
		LOC12 = (x == (*(*a).deleted).key);
		LA15: ;
		if (!LOC12) goto LA16;
		(*(*a).deleted).key = (*(*t)).key;
		(*(*a).deleted).upperbound = (*(*t)).upperbound;
		(*a).deleted = bottom_25362;
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		deallocavlnode_26206(a, (*a).last);
	}
	goto LA10;
	LA16: ;
	{
		NIM_BOOL LOC19;
		LOC19 = 0;
		LOC19 = ((*(*(*t)).link[(((NI) 0))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		if (LOC19) goto LA20;
		LOC19 = ((*(*(*t)).link[(((NI) 1))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		LA20: ;
		if (!LOC19) goto LA21;
		(*(*t)).level -= ((NI) 1);
		{
			if (!((*(*t)).level < (*(*(*t)).link[(((NI) 1))- 0]).level)) goto LA25;
			(*(*(*t)).link[(((NI) 1))- 0]).level = (*(*t)).level;
		}
		LA25: ;
		skew_26376(t);
		skew_26376(&(*(*t)).link[(((NI) 1))- 0]);
		skew_26376(&(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]);
		split_26384(t);
		split_26384(&(*(*t)).link[(((NI) 1))- 0]);
	}
	goto LA10;
	LA21: ;
	LA10: ;
	}BeforeRet: ;
}

N_NIMCALL(void, rawdealloc_39023)(Memregion25330* a, void* p) {
	Basechunk25280* c_39201;
	c_39201 = pageaddr_27267(p);
	{
		NIM_BOOL LOC3;
		Smallchunk25282* c;
		NI s;
		Freecell25272* f;
		LOC3 = 0;
		LOC3 = issmallchunk_27108(c_39201);
		if (!LOC3) goto LA4;
		c = ((Smallchunk25282*) (c_39201));
		s = (*c).Sup.size;
		f = ((Freecell25272*) (p));
		(*f).zerofield = ((NI) 0);
		(*f).next = (*c).freelist;
		(*c).freelist = f;
		{
			if (!((*c).free < s)) goto LA8;
			listadd_33616(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
			(*c).free += s;
		}
		goto LA6;
		LA8: ;
		{
			(*c).free += s;
			{
				if (!((*c).free == (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))))) goto LA13;
				listremove_36402(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
				(*c).Sup.size = ((NI) 4096);
				freebigchunk_28206(a, ((Bigchunk25284*) (c)));
			}
			LA13: ;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		Bigchunk25284* c;
		c = ((Bigchunk25284*) (c_39201));
		(*a).deleted = bottom_25362;
		del_26604(a, &(*a).root, ((NI) ((&(*c).data))));
		freebigchunk_28206(a, c);
	}
	LA1: ;
}

N_NIMCALL(void, dealloc_42028)(Memregion25330* allocator, void* p) {
	void* x;
	x = ((void*) ((NI)((NU32)(((NI) (p))) - (NU32)(((NI)sizeof(Freecell25272))))));
	rawdealloc_39023(allocator, x);
}

N_NOCONV(void, dealloc_8448)(void* p) {
	dealloc_42028((&gch_45459.region), p);
}

static N_INLINE(void, add_43437)(Cellseq43362* s, Cell43346* c) {
	{
		Cell43346** d;
		void* LOC5;
		if (!((*s).cap <= (*s).len)) goto LA3;
		(*s).cap = (NI)((NI)((*s).cap * ((NI) 3)) / ((NI) 2));
		LOC5 = 0;
		LOC5 = alloc_8401(((NI) ((NI)((*s).cap * ((NI) 4)))));
		d = ((Cell43346**) (LOC5));
		memcpy(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)((*s).len * ((NI) 4)))));
		dealloc_8448(((void*) ((*s).d)));
		(*s).d = d;
	}
	LA3: ;
	(*s).d[((*s).len)- 0] = c;
	(*s).len += ((NI) 1);
}

static N_INLINE(void, gcmark_66246)(Gcheap45418* gch, void* p) {
	Cell43346* cell;
	NI c;
	cell = usrtocell_47046(p);
	c = ((NI) (cell));
	{
		Cell43346* objstart;
		void* LOC5;
		if (!((NU32)(((NI) 4096)) < (NU32)(c))) goto LA3;
		LOC5 = 0;
		LOC5 = interiorallocatedptr_40701((&(*gch).region), ((void*) (cell)));
		objstart = ((Cell43346*) (LOC5));
		{
			if (!!((objstart == NIM_NIL))) goto LA8;
			(*objstart).refcount = (NI)((NU32)((*objstart).refcount) + (NU32)(((NI) 8)));
			add_43437((&(*gch).decstack), objstart);
		}
		LA8: ;
	}
	LA3: ;
}

N_CDECL(void, markstackandregisters_68440)(Gcheap45418* gch) {
	jmp_buf registers;
	{
		int LOC3;
		NI max;
		NI sp;
		LOC3 = 0;
		LOC3 = setjmp(registers);
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		max = ((NI) ((*gch).stackbottom));
		sp = ((NI) ((&registers)));
		sp = (NI)(sp & ((NI) -4));
		{
			while (1) {
				if (!((NU32)(sp) < (NU32)((NI)(max - ((NI) 32))))) goto LA7;
				gcmark_66246(gch, ((void**) (sp))[(((NI) 0))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 1))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 2))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 3))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 4))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 5))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 6))- 0]);
				gcmark_66246(gch, ((void**) (sp))[(((NI) 7))- 0]);
				sp = (NI)((NU32)(sp) + (NU32)(((NI) 32)));
			} LA7: ;
		}
		{
			while (1) {
				if (!((NU32)(sp) <= (NU32)(max))) goto LA9;
				gcmark_66246(gch, (*((void**) (sp))));
				sp = (NI)((NU32)(sp) + (NU32)(((NI) 4)));
			} LA9: ;
		}
	}
	LA4: ;
}

N_NIMCALL(void, markthreadstacks_66806)(Gcheap45418* gch) {
}

static N_INLINE(NIM_BOOL, canbecycleroot_47067)(Cell43346* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(NI, nexttry_43521)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI)((NI)(((NI) 5) * h) + ((NI) 1)) & maxhash);
	return result;
}

N_NIMCALL(Pagedesc43354*, cellsetget_43529)(Cellset43358 t, NI key) {
	Pagedesc43354* result;
	NI h;
{	result = 0;
	h = (NI)(((NI) (key)) & t.max);
	{
		while (1) {
			if (!!((t.data[(h)- 0] == NIM_NIL))) goto LA2;
			{
				if (!((*t.data[(h)- 0]).key == key)) goto LA5;
				result = t.data[(h)- 0];
				goto BeforeRet;
			}
			LA5: ;
			h = nexttry_43521(h, t.max);
		} LA2: ;
	}
	result = NIM_NIL;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, excl_44095)(Cellset43358* s, Cell43346* cell) {
	NI u;
	Pagedesc43354* t;
	u = ((NI) (cell));
	t = cellsetget_43529((*s), (NI)((NU32)(u) >> (NU32)(((NI) 12))));
	{
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)((NU32)((NI)((NU32)(u) % (NU32)(((NI) 4096)))) / (NU32)(((NI) 8)));
		(*t).bits[((NI)((NU32)(u) >> (NU32)(((NI) 5))))- 0] = (NI)((*t).bits[((NI)((NU32)(u) >> (NU32)(((NI) 5))))- 0] & (NI)((NU32) ~((NI)((NU32)(((NI) 1)) << (NU32)(((NI) ((NI)(u & ((NI) 31)))))))));
	}
	LA3: ;
}

static N_INLINE(void*, celltousr_47025)(Cell43346* cell) {
	void* result;
	result = 0;
	result = ((void*) ((NI)((NU32)(((NI) (cell))) + (NU32)(((NI)sizeof(Cell43346))))));
	return result;
}

N_NIMCALL(void, preparedealloc_47608)(Cell43346* cell) {
	{
		void* LOC5;
		if (!!(((*(*cell).typ).finalizer == NIM_NIL))) goto LA3;
		gch_45459.recgclock += ((NI) 1);
		LOC5 = 0;
		LOC5 = celltousr_47025(cell);
		((Finalizer) ((*(*cell).typ).finalizer))(LOC5);
		gch_45459.recgclock -= ((NI) 1);
	}
	LA3: ;
}

N_NOINLINE(void, addzct_47017)(Cellseq43362* s, Cell43346* c) {
	{
		if (!((NI)((*c).refcount & ((NI) 4)) == ((NI) 0))) goto LA3;
		(*c).refcount = (NI)((*c).refcount | ((NI) 4));
		add_43437(s, c);
	}
	LA3: ;
}

static N_INLINE(void, rtladdzct_48604)(Cell43346* c) {
	addzct_47017((&gch_45459.zct), c);
}

N_NIMCALL(void, cellsetrawinsert_43558)(Cellset43358 t, Pagedesc43354** data, Pagedesc43354* desc) {
	NI h;
	h = (NI)(((NI) ((*desc).key)) & t.max);
	{
		while (1) {
			if (!!((data[(h)- 0] == NIM_NIL))) goto LA2;
			h = nexttry_43521(h, t.max);
		} LA2: ;
	}
	data[(h)- 0] = desc;
}

N_NIMCALL(void, cellsetenlarge_43812)(Cellset43358* t) {
	NI oldmax;
	Pagedesc43354** n;
	void* LOC1;
	oldmax = (*t).max;
	(*t).max = (NI)((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) - ((NI) 1));
	LOC1 = 0;
	LOC1 = alloc0_8417(((NI) ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 4)))));
	n = ((Pagedesc43354**) (LOC1));
	{
		NI i_43829;
		NI res_43847;
		i_43829 = 0;
		res_43847 = ((NI) 0);
		{
			while (1) {
				if (!(res_43847 <= oldmax)) goto LA4;
				i_43829 = res_43847;
				{
					if (!!(((*t).data[(i_43829)- 0] == NIM_NIL))) goto LA7;
					cellsetrawinsert_43558((*t), n, (*t).data[(i_43829)- 0]);
				}
				LA7: ;
				res_43847 += ((NI) 1);
			} LA4: ;
		}
	}
	dealloc_8448(((void*) ((*t).data)));
	(*t).data = n;
}

N_NIMCALL(Pagedesc43354*, cellsetput_43863)(Cellset43358* t, NI key) {
	Pagedesc43354* result;
	NI h;
	void* LOC19;
{	result = 0;
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			Pagedesc43354* x;
			x = (*t).data[(h)- 0];
			{
				if (!(x == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*x).key == key)) goto LA9;
				result = x;
				goto BeforeRet;
			}
			LA9: ;
			h = nexttry_43521(h, (*t).max);
		}
	} LA1: ;
	{
		NIM_BOOL LOC13;
		LOC13 = 0;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) < (NI)((*t).counter * ((NI) 3)));
		if (LOC13) goto LA14;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) - (*t).counter) < ((NI) 4));
		LA14: ;
		if (!LOC13) goto LA15;
		cellsetenlarge_43812(t);
	}
	LA15: ;
	(*t).counter += ((NI) 1);
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			if (!!(((*t).data[(h)- 0] == NIM_NIL))) goto LA18;
			h = nexttry_43521(h, (*t).max);
		} LA18: ;
	}
	LOC19 = 0;
	LOC19 = alloc0_8417(((NI) (((NI)sizeof(Pagedesc43354)))));
	result = ((Pagedesc43354*) (LOC19));
	(*result).next = (*t).head;
	(*result).key = key;
	(*t).head = result;
	(*t).data[(h)- 0] = result;
	}BeforeRet: ;
	return result;
}

N_NOINLINE(void, incl_44065)(Cellset43358* s, Cell43346* cell) {
	NI u;
	Pagedesc43354* t;
	u = ((NI) (cell));
	t = cellsetput_43863(s, (NI)((NU32)(u) >> (NU32)(((NI) 12))));
	u = (NI)((NU32)((NI)((NU32)(u) % (NU32)(((NI) 4096)))) / (NU32)(((NI) 8)));
	(*t).bits[((NI)((NU32)(u) >> (NU32)(((NI) 5))))- 0] = (NI)((*t).bits[((NI)((NU32)(u) >> (NU32)(((NI) 5))))- 0] | (NI)((NU32)(((NI) 1)) << (NU32)(((NI) ((NI)(u & ((NI) 31)))))));
}

static N_INLINE(void, rtladdcycleroot_47823)(Cell43346* c) {
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		incl_44065((&gch_45459.cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, decref_49004)(Cell43346* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		rtladdzct_48604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_47067(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_47823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

N_NIMCALL(void, markgray_62605)(Cell43346* s) {
	{
		if (!!((((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1)))) goto LA3;
		(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 1));
		forallchildren_47417(s, ((NU8) 5));
	}
	LA3: ;
}

N_NIMCALL(void, scanblack_62804)(Cell43346* s) {
	(*s).refcount = (NI)((*s).refcount & ((NI) -4));
	forallchildren_47417(s, ((NU8) 7));
}

N_NIMCALL(void, scan_63004)(Cell43346* s) {
	{
		if (!(((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1))) goto LA3;
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*s).refcount))) goto LA7;
			scanblack_62804(s);
		}
		goto LA5;
		LA7: ;
		{
			(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 2));
			forallchildren_47417(s, ((NU8) 6));
		}
		LA5: ;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, isallocatedptr_32405)(Memregion25330* a, void* p) {
	NIM_BOOL result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk25280* c_40616;
		LOC3 = 0;
		LOC3 = isaccessible_28018(a, p);
		if (!LOC3) goto LA4;
		c_40616 = pageaddr_27267(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_27131(c_40616);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk25282* c;
				NI offset;
				NIM_BOOL LOC16;
				NIM_BOOL LOC17;
				LOC13 = 0;
				LOC13 = issmallchunk_27108(c_40616);
				if (!LOC13) goto LA14;
				c = ((Smallchunk25282*) (c_40616));
				offset = (NI)((NU32)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU32)((NI)(((NI)sizeof(Smallchunk25282)) - ((NI) 8))));
				LOC16 = 0;
				LOC17 = 0;
				LOC17 = ((NU32)(offset) < (NU32)((*c).acc));
				if (!(LOC17)) goto LA18;
				LOC17 = ((NI)((NU32)(offset) % (NU32)((*c).Sup.size)) == ((NI) 0));
				LA18: ;
				LOC16 = LOC17;
				if (!(LOC16)) goto LA19;
				LOC16 = ((NU32)(((NI) 1)) < (NU32)((*((Freecell25272*) (p))).zerofield));
				LA19: ;
				result = LOC16;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk25284* c;
				NIM_BOOL LOC21;
				c = ((Bigchunk25284*) (c_40616));
				LOC21 = 0;
				LOC21 = (p == ((void*) ((&(*c).data))));
				if (!(LOC21)) goto LA22;
				LOC21 = ((NU32)(((NI) 1)) < (NU32)((*((Freecell25272*) (p))).zerofield));
				LA22: ;
				result = LOC21;
			}
			LA11: ;
		}
		LA9: ;
	}
	LA4: ;
	return result;
}

N_NIMCALL(void, freecycliccell_61827)(Gcheap45418* gch, Cell43346* c) {
	preparedealloc_47608(c);
	rawdealloc_39023((&(*gch).region), ((void*) (c)));
}

N_NIMCALL(void, collectwhite_63204)(Cell43346* s) {
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isallocatedptr_32405((&gch_45459.region), ((void*) (s)));
		if (!(LOC3)) goto LA4;
		LOC3 = (((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		(*s).refcount = (NI)((*s).refcount & ((NI) -4));
		forallchildren_47417(s, ((NU8) 8));
		freecycliccell_61827((&gch_45459), s);
	}
	LA5: ;
}

N_NIMCALL(void, dooperation_47421)(void* p, NU8 op) {
	Cell43346* c;
{	{
		if (!(p == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	c = usrtocell_47046(p);
	switch (op) {
	case ((NU8) 2):
	{
		decref_49004(c);
	}
	break;
	case ((NU8) 3):
	{
		add_43437((&gch_45459.tempstack), c);
	}
	break;
	case ((NU8) 4):
	{
		(*c).refcount = (NI)((NU32)((*c).refcount) - (NU32)(((NI) 8)));
	}
	break;
	case ((NU8) 5):
	{
		(*c).refcount = (NI)((NU32)((*c).refcount) - (NU32)(((NI) 8)));
		markgray_62605(c);
	}
	break;
	case ((NU8) 6):
	{
		scan_63004(c);
	}
	break;
	case ((NU8) 7):
	{
		(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
		{
			if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 0)))) goto LA13;
			scanblack_62804(c);
		}
		LA13: ;
	}
	break;
	case ((NU8) 8):
	{
		collectwhite_63204(c);
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	case ((NU8) 1):
	{
	}
	break;
	}
	}BeforeRet: ;
}

N_NIMCALL(NI, getdiscriminant_23204)(void* aa, TNimNode* n) {
	NI result;
	NI d;
	NI a;
{	result = 0;
	d = 0;
	a = ((NI) (aa));
	switch ((*(*n).typ).size) {
	case ((NI) 1):
	{
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	case ((NI) 2):
	{
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	case ((NI) 4):
	{
		d = ((NI) ((*((NI32*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	default:
	{
	}
	break;
	}
	result = d;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TNimNode*, selectbranch_23610)(void* aa, TNimNode* n) {
	TNimNode* result;
	NI discr;
	result = 0;
	discr = getdiscriminant_23204(aa, n);
	{
		if (!((NU32)(discr) < (NU32)((*n).len))) goto LA3;
		result = (*n).sons[(discr)- 0];
		{
			if (!(result == NIM_NIL)) goto LA7;
			result = (*n).sons[((*n).len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).sons[((*n).len)- 0];
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, forallslotsaux_51608)(void* dest, TNimNode* n, NU8 op) {
	NI d;
	d = ((NI) (dest));
	switch ((*n).kind) {
	case ((NU8) 1):
	{
		forallchildrenaux_47425(((void*) ((NI)((NU32)(d) + (NU32)((*n).offset)))), (*n).typ, op);
	}
	break;
	case ((NU8) 2):
	{
		{
			NI i_51634;
			NI HEX3Atmp_51806;
			NI res_51809;
			i_51634 = 0;
			HEX3Atmp_51806 = 0;
			HEX3Atmp_51806 = (NI)((*n).len - ((NI) 1));
			res_51809 = ((NI) 0);
			{
				while (1) {
					if (!(res_51809 <= HEX3Atmp_51806)) goto LA5;
					i_51634 = res_51809;
					{
						if (!((*(*n).sons[(i_51634)- 0]).kind == ((NU8) 1))) goto LA8;
						{
							if (!((*(*(*n).sons[(i_51634)- 0]).typ).kind == ((NU8) 22) || (*(*(*n).sons[(i_51634)- 0]).typ).kind == ((NU8) 28) || (*(*(*n).sons[(i_51634)- 0]).typ).kind == ((NU8) 24))) goto LA12;
							dooperation_47421((*((void**) ((NI)((NU32)(d) + (NU32)((*(*n).sons[(i_51634)- 0]).offset))))), op);
						}
						goto LA10;
						LA12: ;
						{
							forallchildrenaux_47425(((void*) ((NI)((NU32)(d) + (NU32)((*(*n).sons[(i_51634)- 0]).offset)))), (*(*n).sons[(i_51634)- 0]).typ, op);
						}
						LA10: ;
					}
					goto LA6;
					LA8: ;
					{
						forallslotsaux_51608(dest, (*n).sons[(i_51634)- 0], op);
					}
					LA6: ;
					res_51809 += ((NI) 1);
				} LA5: ;
			}
		}
	}
	break;
	case ((NU8) 3):
	{
		TNimNode* m;
		m = selectbranch_23610(dest, n);
		{
			if (!!((m == NIM_NIL))) goto LA19;
			forallslotsaux_51608(dest, m, op);
		}
		LA19: ;
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	}
}

N_NIMCALL(void, forallchildrenaux_47425)(void* dest, TNimType* mt, NU8 op) {
	NI d;
{	d = ((NI) (dest));
	{
		if (!(dest == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!!((((*mt).flags &(1<<((((NU8) 0))&7)))!=0))) goto LA7;
		switch ((*mt).kind) {
		case ((NU8) 22):
		case ((NU8) 28):
		case ((NU8) 24):
		{
			dooperation_47421((*((void**) (d))), op);
		}
		break;
		case ((NU8) 17):
		case ((NU8) 18):
		{
			forallslotsaux_51608(dest, (*mt).node, op);
		}
		break;
		case ((NU8) 16):
		case ((NU8) 4):
		case ((NU8) 27):
		{
			{
				NI i_51851;
				NI HEX3Atmp_51874;
				NI res_51877;
				i_51851 = 0;
				HEX3Atmp_51874 = 0;
				HEX3Atmp_51874 = (NI)((NI)((*mt).size / (*(*mt).base).size) - ((NI) 1));
				res_51877 = ((NI) 0);
				{
					while (1) {
						if (!(res_51877 <= HEX3Atmp_51874)) goto LA14;
						i_51851 = res_51877;
						forallchildrenaux_47425(((void*) ((NI)((NU32)(d) + (NU32)((NI)((NU32)(i_51851) * (NU32)((*(*mt).base).size)))))), (*mt).base, op);
						res_51877 += ((NI) 1);
					} LA14: ;
				}
			}
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA7: ;
	}BeforeRet: ;
}

N_NIMCALL(void, forallchildren_47417)(Cell43346* cell, NU8 op) {
	TY3889 marker;
	marker = (*(*cell).typ).marker;
	{
		void* LOC5;
		if (!!((marker == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = celltousr_47025(cell);
		marker(LOC5, ((NI) (op)));
	}
	goto LA1;
	LA3: ;
	{
		switch ((*(*cell).typ).kind) {
		case ((NU8) 22):
		{
			void* LOC8;
			LOC8 = 0;
			LOC8 = celltousr_47025(cell);
			forallchildrenaux_47425(LOC8, (*(*cell).typ).base, op);
		}
		break;
		case ((NU8) 24):
		{
			NI d;
			void* LOC10;
			TGenericSeq* s;
			LOC10 = 0;
			LOC10 = celltousr_47025(cell);
			d = ((NI) (LOC10));
			s = ((TGenericSeq*) (d));
			{
				if (!!((s == NIM_NIL))) goto LA13;
				{
					NI i_52635;
					NI HEX3Atmp_52668;
					NI res_52671;
					i_52635 = 0;
					HEX3Atmp_52668 = 0;
					HEX3Atmp_52668 = (NI)((*s).len - ((NI) 1));
					res_52671 = ((NI) 0);
					{
						while (1) {
							if (!(res_52671 <= HEX3Atmp_52668)) goto LA17;
							i_52635 = res_52671;
							forallchildrenaux_47425(((void*) ((NI)((NU32)((NI)((NU32)(d) + (NU32)((NI)((NU32)(i_52635) * (NU32)((*(*(*cell).typ).base).size))))) + (NU32)(((NI) 8))))), (*(*cell).typ).base, op);
							res_52671 += ((NI) 1);
						} LA17: ;
					}
				}
			}
			LA13: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, collectzct_65612)(Gcheap45418* gch) {
	NIM_BOOL result;
	NI* L;
	result = 0;
	L = (&(*gch).zct.len);
	{
		while (1) {
			Cell43346* c;
			if (!(((NI) 0) < (*L))) goto LA2;
			c = (*gch).zct.d[(((NI) 0))- 0];
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			(*gch).zct.d[(((NI) 0))- 0] = (*gch).zct.d[((NI)((*L) - ((NI) 1)))- 0];
			(*L) -= ((NI) 1);
			{
				if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA5;
				{
					NIM_BOOL LOC9;
					LOC9 = 0;
					LOC9 = canbecycleroot_47067(c);
					if (!LOC9) goto LA10;
					excl_44095((&(*gch).cycleroots), c);
				}
				LA10: ;
				preparedealloc_47608(c);
				forallchildren_47417(c, ((NU8) 2));
				rawdealloc_39023((&(*gch).region), ((void*) (c)));
			}
			LA5: ;
		} LA2: ;
	}
	result = NIM_TRUE;
	return result;
}

N_NIMCALL(void, markroots_63405)(Gcheap45418* gch) {
	NI tabsize;
	tabsize = ((NI) 0);
	{
		Cell43346* s_63410;
		Cellset43358 HEX3Atmp_63437;
		Pagedesc43354* r_63442;
		s_63410 = 0;
		memset((void*)(&HEX3Atmp_63437), 0, sizeof(HEX3Atmp_63437));
		HEX3Atmp_63437 = (*gch).cycleroots;
		r_63442 = HEX3Atmp_63437.head;
		{
			while (1) {
				NI i_63444;
				if (!!((r_63442 == NIM_NIL))) goto LA3;
				i_63444 = ((NI) 0);
				{
					while (1) {
						NI w_63446;
						NI j_63448;
						if (!(i_63444 <= ((NI) 15))) goto LA5;
						w_63446 = (*r_63442).bits[(i_63444)- 0];
						j_63448 = ((NI) 0);
						{
							while (1) {
								if (!!((w_63446 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_63446 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_63410 = ((Cell43346*) ((NI)((NI)((NU32)((*r_63442).key) << (NU32)(((NI) 12))) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_63444) << (NU32)(((NI) 5)))) + (NU32)(j_63448))) * (NU32)(((NI) 8))))));
									tabsize += ((NI) 1);
									{
										NIM_BOOL LOC14;
										LOC14 = 0;
										LOC14 = (((NI) ((NI)((*s_63410).refcount & ((NI) 3)))) == ((NI) 3));
										if (!(LOC14)) goto LA15;
										LOC14 = ((NU32)(((NI) 8)) <= (NU32)((*s_63410).refcount));
										LA15: ;
										if (!LOC14) goto LA16;
										markgray_62605(s_63410);
									}
									goto LA12;
									LA16: ;
									{
										excl_44095((&(*gch).cycleroots), s_63410);
										{
											if (!((*s_63410).refcount == ((NI) 0))) goto LA21;
											freecycliccell_61827(gch, s_63410);
										}
										LA21: ;
									}
									LA12: ;
								}
								LA10: ;
								j_63448 += ((NI) 1);
								w_63446 = (NI)((NU32)(w_63446) >> (NU32)(((NI) 1)));
							} LA7: ;
						}
						i_63444 += ((NI) 1);
					} LA5: ;
				}
				r_63442 = (*r_63442).next;
			} LA3: ;
		}
	}
	(*gch).stat.cycletablesize = (((*gch).stat.cycletablesize >= tabsize) ? (*gch).stat.cycletablesize : tabsize);
}

N_NIMCALL(void, collectroots_65801)(Gcheap45418* gch) {
	{
		Cell43346* s_65805;
		Cellset43358 HEX3Atmp_65807;
		Pagedesc43354* r_65812;
		s_65805 = 0;
		memset((void*)(&HEX3Atmp_65807), 0, sizeof(HEX3Atmp_65807));
		HEX3Atmp_65807 = (*gch).cycleroots;
		r_65812 = HEX3Atmp_65807.head;
		{
			while (1) {
				NI i_65814;
				if (!!((r_65812 == NIM_NIL))) goto LA3;
				i_65814 = ((NI) 0);
				{
					while (1) {
						NI w_65816;
						NI j_65818;
						if (!(i_65814 <= ((NI) 15))) goto LA5;
						w_65816 = (*r_65812).bits[(i_65814)- 0];
						j_65818 = ((NI) 0);
						{
							while (1) {
								if (!!((w_65816 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_65816 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_65805 = ((Cell43346*) ((NI)((NI)((NU32)((*r_65812).key) << (NU32)(((NI) 12))) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_65814) << (NU32)(((NI) 5)))) + (NU32)(j_65818))) * (NU32)(((NI) 8))))));
									collectwhite_63204(s_65805);
								}
								LA10: ;
								j_65818 += ((NI) 1);
								w_65816 = (NI)((NU32)(w_65816) >> (NU32)(((NI) 1)));
							} LA7: ;
						}
						i_65814 += ((NI) 1);
					} LA5: ;
				}
				r_65812 = (*r_65812).next;
			} LA3: ;
		}
	}
}

N_NIMCALL(void, deinit_43493)(Cellset43358* s) {
	Pagedesc43354* it;
	it = (*s).head;
	{
		while (1) {
			Pagedesc43354* n;
			if (!!((it == NIM_NIL))) goto LA2;
			n = (*it).next;
			dealloc_8448(((void*) (it)));
			it = n;
		} LA2: ;
	}
	(*s).head = NIM_NIL;
	dealloc_8448(((void*) ((*s).data)));
	(*s).data = NIM_NIL;
	(*s).counter = ((NI) 0);
}

N_NIMCALL(void, cellsetreset_51601)(Cellset43358* s) {
	deinit_43493(s);
	init_43482(s);
}

N_NIMCALL(void, collectcycles_65844)(Gcheap45418* gch) {
	{
		while (1) {
			NIM_BOOL LOC3;
			if (!(((NI) 0) < (*gch).zct.len)) goto LA2;
			LOC3 = 0;
			LOC3 = collectzct_65612(gch);
		} LA2: ;
	}
	markroots_63405(gch);
	{
		Cell43346* s_66001;
		Cellset43358 HEX3Atmp_66203;
		Pagedesc43354* r_66208;
		s_66001 = 0;
		memset((void*)(&HEX3Atmp_66203), 0, sizeof(HEX3Atmp_66203));
		HEX3Atmp_66203 = (*gch).cycleroots;
		r_66208 = HEX3Atmp_66203.head;
		{
			while (1) {
				NI i_66210;
				if (!!((r_66208 == NIM_NIL))) goto LA6;
				i_66210 = ((NI) 0);
				{
					while (1) {
						NI w_66212;
						NI j_66214;
						if (!(i_66210 <= ((NI) 15))) goto LA8;
						w_66212 = (*r_66208).bits[(i_66210)- 0];
						j_66214 = ((NI) 0);
						{
							while (1) {
								if (!!((w_66212 == ((NI) 0)))) goto LA10;
								{
									if (!!((((NI) ((NI)(w_66212 & ((NI) 1)))) == ((NI) 0)))) goto LA13;
									s_66001 = ((Cell43346*) ((NI)((NI)((NU32)((*r_66208).key) << (NU32)(((NI) 12))) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_66210) << (NU32)(((NI) 5)))) + (NU32)(j_66214))) * (NU32)(((NI) 8))))));
									scan_63004(s_66001);
								}
								LA13: ;
								j_66214 += ((NI) 1);
								w_66212 = (NI)((NU32)(w_66212) >> (NU32)(((NI) 1)));
							} LA10: ;
						}
						i_66210 += ((NI) 1);
					} LA8: ;
				}
				r_66208 = (*r_66208).next;
			} LA6: ;
		}
	}
	collectroots_65801(gch);
	cellsetreset_51601((&(*gch).cycleroots));
}

N_NIMCALL(NI, gettotalmem_9095)(void) {
	NI result;
{	result = 0;
	result = gch_45459.region.currmem;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getfreemem_9093)(void) {
	NI result;
	result = 0;
	result = gch_45459.region.freemem;
	return result;
}

N_NIMCALL(NI, getoccupiedmem_9091)(void) {
	NI result;
	NI LOC1;
	NI LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = gettotalmem_9095();
	LOC2 = 0;
	LOC2 = getfreemem_9093();
	result = (NI)(LOC1 - LOC2);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, unmarkstackandregisters_70811)(Gcheap45418* gch) {
	Cell43346** d;
	d = (*gch).decstack.d;
	{
		NI i_70826;
		NI HEX3Atmp_71002;
		NI res_71005;
		i_70826 = 0;
		HEX3Atmp_71002 = 0;
		HEX3Atmp_71002 = (NI)((*gch).decstack.len - ((NI) 1));
		res_71005 = ((NI) 0);
		{
			while (1) {
				if (!(res_71005 <= HEX3Atmp_71002)) goto LA3;
				i_70826 = res_71005;
				decref_49004(d[(i_70826)- 0]);
				res_71005 += ((NI) 1);
			} LA3: ;
		}
	}
	(*gch).decstack.len = ((NI) 0);
}

N_NIMCALL(void, collectctbody_71021)(Gcheap45418* gch) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_67201();
	(*gch).stat.maxstacksize = (((*gch).stat.maxstacksize >= LOC1) ? (*gch).stat.maxstacksize : LOC1);
	prepareforinteriorpointerchecking_40694((&(*gch).region));
	markstackandregisters_68440(gch);
	markthreadstacks_66806(gch);
	(*gch).stat.maxstackcells = (((*gch).stat.maxstackcells >= (*gch).decstack.len) ? (*gch).stat.maxstackcells : (*gch).decstack.len);
	(*gch).stat.stackscans += ((NI) 1);
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = collectzct_65612(gch);
		if (!LOC4) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC10;
			NI LOC14;
			LOC9 = 0;
			LOC10 = 0;
			LOC10 = getoccupiedmem_43268((&(*gch).region));
			LOC9 = ((*gch).cyclethreshold <= LOC10);
			if (LOC9) goto LA11;
			LOC9 = NIM_FALSE;
			LA11: ;
			if (!LOC9) goto LA12;
			collectcycles_65844(gch);
			(*gch).stat.cyclecollections += ((NI) 1);
			LOC14 = 0;
			LOC14 = getoccupiedmem_9091();
			(*gch).cyclethreshold = ((((NI) 4194304) >= (NI)(LOC14 * ((NI) 2))) ? ((NI) 4194304) : (NI)(LOC14 * ((NI) 2)));
			(*gch).stat.maxthreshold = (((*gch).stat.maxthreshold >= (*gch).cyclethreshold) ? (*gch).stat.maxthreshold : (*gch).cyclethreshold);
		}
		LA12: ;
	}
	LA5: ;
	unmarkstackandregisters_70811(gch);
}

N_NIMCALL(void, collectct_47410)(Gcheap45418* gch) {
	NI stackmarkcosts;
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_67201();
	stackmarkcosts = (((NI)(LOC1 / ((NI) 64)) >= ((NI) 500)) ? (NI)(LOC1 / ((NI) 64)) : ((NI) 500));
	{
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC6;
		NIM_BOOL LOC8;
		NI LOC10;
		LOC4 = 0;
		LOC5 = 0;
		LOC6 = 0;
		LOC6 = (stackmarkcosts <= (*gch).zct.len);
		if (LOC6) goto LA7;
		LOC8 = 0;
		LOC8 = NIM_TRUE;
		if (!(LOC8)) goto LA9;
		LOC10 = 0;
		LOC10 = getoccupiedmem_43268((&(*gch).region));
		LOC8 = ((*gch).cyclethreshold <= LOC10);
		LA9: ;
		LOC6 = LOC8;
		LA7: ;
		LOC5 = LOC6;
		if (LOC5) goto LA11;
		LOC5 = NIM_FALSE;
		LA11: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA12;
		LOC4 = ((*gch).recgclock == ((NI) 0));
		LA12: ;
		if (!LOC4) goto LA13;
		collectctbody_71021(gch);
	}
	LA13: ;
}

static N_INLINE(void, addnewobjtozct_52687)(Cell43346* res, Gcheap45418* gch) {
	NI L;
	Cell43346** d;
{	L = (*gch).zct.len;
	d = (*gch).zct.d;
	{
		Cell43346* c;
		if (!(((NI) 8) < L)) goto LA3;
		c = 0;
		c = d[((NI)(L - ((NI) 1)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA7;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 1)))- 0] = res;
			goto BeforeRet;
		}
		LA7: ;
		c = d[((NI)(L - ((NI) 2)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA11;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 2)))- 0] = res;
			goto BeforeRet;
		}
		LA11: ;
		c = d[((NI)(L - ((NI) 3)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA15;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 3)))- 0] = res;
			goto BeforeRet;
		}
		LA15: ;
		c = d[((NI)(L - ((NI) 4)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA19;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 4)))- 0] = res;
			goto BeforeRet;
		}
		LA19: ;
		c = d[((NI)(L - ((NI) 5)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA23;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 5)))- 0] = res;
			goto BeforeRet;
		}
		LA23: ;
		c = d[((NI)(L - ((NI) 6)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA27;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 6)))- 0] = res;
			goto BeforeRet;
		}
		LA27: ;
		c = d[((NI)(L - ((NI) 7)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA31;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 7)))- 0] = res;
			goto BeforeRet;
		}
		LA31: ;
		c = d[((NI)(L - ((NI) 8)))- 0];
		{
			if (!((NU32)(((NI) 8)) <= (NU32)((*c).refcount))) goto LA35;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 8)))- 0] = res;
			goto BeforeRet;
		}
		LA35: ;
		add_43437((&(*gch).zct), res);
	}
	goto LA1;
	LA3: ;
	{
		d[(L)- 0] = res;
		(*gch).zct.len += ((NI) 1);
	}
	LA1: ;
	}BeforeRet: ;
}

N_NIMCALL(void*, rawnewobj_53204)(TNimType* typ, NI size, Gcheap45418* gch) {
	void* result;
	Cell43346* res;
	void* LOC1;
	result = 0;
	collectct_47410(gch);
	LOC1 = 0;
	LOC1 = rawalloc_32701((&(*gch).region), (NI)(size + ((NI)sizeof(Cell43346))));
	res = ((Cell43346*) (LOC1));
	(*res).typ = typ;
	(*res).refcount = ((NI) 4);
	addnewobjtozct_52687(res, gch);
	result = celltousr_47025(res);
	return result;
}

N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_53204(typ, size, (&gch_45459));
	return result;
}

N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3;
		s = ((NI) 7);
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObjNoInit((&strdesc_13601), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}

N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src) {
	NimStringDesc* result;
	result = 0;
	{
		if (!!((src == NIM_NIL))) goto LA3;
		{
			if (!!(((NI)((*src).Sup.reserved & ((NI) (-2147483647 -1))) == ((NI) 0)))) goto LA7;
			result = src;
		}
		goto LA5;
		LA7: ;
		{
			result = rawNewStringNoInit((*src).Sup.len);
			(*result).Sup.len = (*src).Sup.len;
			memcpy(((NCSTRING) ((*result).data)), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
		}
		LA5: ;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void*, newObj)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_53204(typ, size, (&gch_45459));
	zeroMem(result, ((NI) (size)));
	return result;
}

N_NIMCALL(NimStringDesc*, rawNewString)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3;
		s = ((NI) 7);
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObj((&strdesc_13601), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void) {
	nimvm_6690 = NIM_FALSE;
	strdesc_13601.size = ((NI) 4);
	strdesc_13601.kind = ((NU8) 28);
	strdesc_13601.flags = 2;
	initallocator_13001();
	initStackBottom();
	initgc_12801();
	bumppointer_25207 = ((NI) (theheap_25205));
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void) {
}
